apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-moderated-deployment
  labels:
    app: item-moderated
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-moderated
  template:
    metadata:
      labels:
        app: item-moderated
    spec:
      volumes:
        - name: redis-volume
          secret:
            secretName: redis-secret
      containers:
        - name: item-moderated
          image: brianalexander/item-moderated
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["python"]
          args: ["./item_moderated.py"]
          volumeMounts:
            - name: redis-volume
              mountPath: /etc/secrets/redis
