kind: Service
apiVersion: v1
metadata:
 name: elasticsearch
spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
 name: elasticsearch
subsets:
 - addresses:
     - ip: 192.168.1.196
   ports:
     - port: 9200
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres
# spec:
#   type: ExternalName
#   externalName: 192.168.1.89
#   ports:
#     - protocol: TCP
#       port: 5432