kind: Service
apiVersion: v1
metadata:
 name: redis
spec:
 type: ClusterIP
 ports:
 - port: 6379
   targetPort: 6379
---
kind: Endpoints
apiVersion: v1
metadata:
 name: redis
subsets:
 - addresses:
     - ip: 192.168.1.196
   ports:
     - port: 6379
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
# spec:
#   type: ExternalName
#   externalName: 192.168.1.89
#   ports:
#     - protocol: TCP
#       port: 6379
